kotlin.code.style=official

#Gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4G"

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#MPP
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true


kotlin.incremental.native=true
kotlin.native.cacheKind=static

kotlin.apple.xcodeCompatibility.nowarn=true

# to ignore the native "Kotlin/Native targets cannot be built on this machine and are disabled" warning
kotlin.native.ignoreDisabledTargets=true

# Disable since cross-compilation currently doesn't work with cinterop which we need
kotlin.native.enableKlibsCrossCompilation=false
